language: java
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "mvn deploy --settings target/travis/settings.xml"
sudo: false

branches:
  except:
    - travis
env:
  global:
    - secure: "j/n0lLFSsSIbSN6EywHOrG+v+CwIuHNRXOliYExdvuJBmc2M4sCsAFAVVb4BoYeBU4PUA5YZ0J6bc+oTajXgIiTdCL8OuEFkq+t4j2P+kLQCKTl/hYnamdksyVKjs616gL3Oe1BLRFWJKGTN6FvWKH5bOgcI08priHN36u/hL1w="
    - secure: "O+TCNcfvT9N51kkKmN7bvKvDXRvtei1NxF4PALFdOPSDiqaj4hsC26wg9TKP0+ulmVP6nq2znOG2Pe2G+keYBPaE/tKJiem0bb1ZCeZtGhrtoChYfyt+TJlqLf63OiBcOWF934eJ+p9fSkDnNMbsv6e6ngaV1L1E74Sm876XyxA="